baseUrl: /
languageCode: en-gb
theme: terminal
paginate: 5
publishDir: docs

params:
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: green
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true

languages:
  en:
    languageName: English
    title: oli m-c
    subtitle: minimal code, happy users
    keywords: ''
    menuMore: show
    readMore: read
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: oli m-c
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: about me
        url: /about
      - identifier: ideas
        name: some ideas
        url: /ideas
      - identifier: blog
        name: blog
        url: /posts
