baseURL: 'https://olimc.co.uk'
title: oli m-c
paginate: 5
theme: hugo-PaperMod

publishDir: 'docs'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

params:
  homeInfoParams:
      Title: 'Oli M-C'
      enabled: true
      Content1: 'professional software developer, amateur cyclist.'
      Content2: 'writing the least amount of code that makes users happy.'
      imageUrl: "<image link>" # optional
      imageTitle: "me" # optional
  disableThemeToggle: true
  defaultTheme: dark
