baseURL: 'https://olimc.co.uk'
title: oli m-c
paginate: 5
theme: hugo-PaperMod

publishDir: 'docs'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

params:
  showNav: true
  homeInfoParams:
      Title: 'Oli M-C'
      enabled: true
      subTitle: 'blah'
      Content1: 'writing the least amount of code that makes users happy'
      Content2: 'python developer, with full stack ambitions. [github](http://www.github.com/sbmooc)|<a href="/omc_cv_nov20.pdf" download>cv</a>'
      imageUrl: "<image link>" # optional
      imageTitle: "me" # optional
  disableThemeToggle: true
  defaultTheme: dark
markup:
  goldmark:
    renderer:
      unsafe: true
